export const GET_ALL_SCHOOLS = Symbol('GET_ALL_SCHOOLS')
export const GET_ALL_STUDENTS = Symbol('GET_ALL_STUDENTS')
export const GET_SCHOOL = Symbol('GET_SCHOOL')
export const GET_STUDENT = Symbol('GET_STUDENT')
export const UPDATE_SCHOOL = Symbol('CREATE_SCHOOL')
export const UPDATE_STUDENT = Symbol('CREATE_STUDENT')
